### ISSUE TITLE
Provide option for encrypted session

### ISSUE THREAD

**Issue by whyallyn** [lixxu/pyldaplite#1]
The current implementation of this library defaults to an unencrypted session such that the username and password are passed in plaintext. If would be better to not hardcode the [server URL to use "ldap"](https://github.com/lixxu/pyldaplite/blob/master/pyldaplite/__init__.py#L16) but allow an option to use LDAPS.

**Comment by lixxu** [comment]
updated, thanks

**Comment by whyallyn** [comment]
Awesome! Thanks for the fast response!
